### ISSUE TITLE
Allow URLRequest & URL

### ISSUE THREAD

**Issue by BrunoMiguens** [rwbutler/Hyperconnectivity#10]
It would be helpful if the `checkConnectivity(of:using:)` used either URLs or URLRequests. However, the code is mostly the same if it simply allows providing either one of those options.

In my case, the health check available is a POST which requires me to configure an URLRequest. It also would allow adding headers and other helpful information to the requests in case someone needs to ping private or secure instances without triggering errors or creating issues. 

Also, in my case, if I do perform a GET to this health check endpoint, I'll trigger errors on the server side since the GET is not exposed.

I can open an MR for this if it helps.

**Comment by rwbutler** [comment]
Hi @BrunoMiguens thanks for the PR, have addressed on that but have now implemented a change which means that you should be able to use `URL` objects or `URLRequest` objects in 1.2.0. Thanks again.
